import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter()

  const handleCreateRandomRoom = () => {
    const room = Math.random().toString(36).substring(2, 15)
    router.push(`/rooms/${room}`)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen justify-center items-center">
        <button onClick={handleCreateRandomRoom} className="btn btn-primary">
          Create new room
        </button>
      </main>
    </div>
  )
}

export default Home
